// Bundles the client into a single artifact the Worker inlines, and vendors the
// KaTeX stylesheet + fonts + favicon alongside it.
//
// Output is one generated TypeScript module (src/generated/bundle.ts, gitignored)
// rather than wrangler module `rules`, so there is nothing to configure and the
// Worker just imports strings.
import esbuild from "esbuild";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const root = path.dirname(fileURLToPath(import.meta.url));
const katexDist = path.join(root, "node_modules/katex/dist");
const outDir = path.join(root, "src/generated");
const faviconSource = path.join(root, "assets/favicon-1024.png");

const asTsString = (value) => JSON.stringify(value);

// --- client bundle -----------------------------------------------------------
const bundled = await esbuild.build({
  entryPoints: [path.join(root, "src/client/main.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2022"],
  write: false,
  logLevel: "warning",
});
const clientJs = bundled.outputFiles[0].text;

// --- katex stylesheet --------------------------------------------------------
// Rewrite each @font-face src list down to the woff2 alone, pointed at the
// Worker's `?font=` handler. Dropping the woff/ttf fallbacks avoids 404s for
// formats no target browser needs (iPhone 13, current Chrome/Edge).
let katexCss = await fs.readFile(path.join(katexDist, "katex.min.css"), "utf8");
katexCss = katexCss.replace(
  /url\(fonts\/(KaTeX_[\w-]+)\.woff2\)\s*format\("woff2"\)(?:\s*,\s*url\(fonts\/[^)]+\)\s*format\("[^"]+"\))*/g,
  (_match, family) => `url("/?font=${family}") format("woff2")`,
);

const leftoverFontUrls = katexCss.match(/url\(fonts\//g);
if (leftoverFontUrls) {
  throw new Error(
    `katex.min.css still has ${leftoverFontUrls.length} unrewritten font url(); the @font-face shape changed`,
  );
}

// --- fonts -------------------------------------------------------------------
const fontDir = path.join(katexDist, "fonts");
const fontFiles = (await fs.readdir(fontDir)).filter((f) => f.endsWith(".woff2"));
const fonts = {};
for (const file of fontFiles) {
  fonts[path.basename(file, ".woff2")] = (
    await fs.readFile(path.join(fontDir, file))
  ).toString("base64");
}

// --- favicon -----------------------------------------------------------------
// Downscaled from the 1024x1024 original; the full-size file never ships.
const favicons = {};
await fs.mkdir(path.join(root, ".cache"), { recursive: true });
for (const size of [32, 180]) {
  const scaled = path.join(root, `.cache/favicon-${size}.png`);
  await run("sips", ["-z", String(size), String(size), faviconSource, "--out", scaled]);
  favicons[size] = (await fs.readFile(scaled)).toString("base64");
}

// --- emit --------------------------------------------------------------------
const fontEntries = Object.entries(fonts)
  .map(([name, b64]) => `  ${asTsString(name)}: ${asTsString(b64)},`)
  .join("\n");
const faviconEntries = Object.entries(favicons)
  .map(([size, b64]) => `  ${asTsString(size)}: ${asTsString(b64)},`)
  .join("\n");

await fs.mkdir(outDir, { recursive: true });
await fs.writeFile(
  path.join(outDir, "bundle.ts"),
  `// GENERATED by build.mjs -- do not edit, do not commit.
export const CLIENT_JS = ${asTsString(clientJs)};

export const KATEX_CSS = ${asTsString(katexCss)};

export const KATEX_FONTS_BASE64: Record<string, string> = {
${fontEntries}
};

export const FAVICON_BASE64: Record<string, string> = {
${faviconEntries}
};
`,
  "utf8",
);

const kb = (n) => `${(n / 1024).toFixed(1)} kb`;
const fontBytes = Object.values(fonts).reduce((a, b) => a + b.length, 0);
console.log(
  [
    `  client js    ${kb(clientJs.length)}`,
    `  katex css    ${kb(katexCss.length)}`,
    `  fonts        ${kb(fontBytes)} base64 (${fontFiles.length} files)`,
    `  favicons     ${kb(Object.values(favicons).reduce((a, b) => a + b.length, 0))} base64`,
  ].join("\n"),
);
